name: Run Matrix Build for Nav

on:
  push:
    branches:
      - fix-38

jobs:
  build-test:
    name: Test npm (Node ${{ matrix.node-version}}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12, 14, 16]
    steps:
      - name: Enable longpaths when the OS is windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
        
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Clean global cache
        run: npm cache clean --force
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Elm 0.19.1
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - name: Install/Update Dependencies
        run: yarn

      - name: Test packages
        run: yarn build
