name: Run tests

# Run tests in all the packages.

on:
  pull_request:
    paths:
      - packages/**
      - .github/workflows/pr-test.yml # This file

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Elm 0.19.1
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1

      - name: Install/Update Dependencies
        run: yarn

      - name: Test packages
        run: yarn test
