name: Publish Navigations Code

on:
  push:
    branches:
      - main
    paths:
      - "navigation/src/**"
      - "navigation/package.json"
      - "navigation/elm.json"
      - ".github/workflows/publish-navigation.yml" # This file

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: ./navigation
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install and set up Elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - name: Install and build
        run: |
          npm ci
          npm run build

      # We can't upload the entire public/ folder because it has other content
      # that helps us run the site locally.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-data
          path: |
            navigation/public/desktopnav-elm.js
            navigation/public/mobilenav-elm.js

  push:
    runs-on: ubuntu-latest
    name: Push to branch
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-data
          path: build

      - name: Push to new Github Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: navigation # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Scrolling Terrain build: ({sha})\n{msg}" # The commit message
