name: Publish or PR

# This workflow analyzes a commit to main
# and if there is a changeset, will create a PR
# else, it will publish

on:
  push:
    branches:
      - main

jobs:
  pr-from-commit:
    name: Publish or PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup Elm 0.19.1
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - name: Install/Update Dependencies
        run: yarn

      - name: Test packages
        run: yarn test

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
