name: PR from Commit on Main

# This workflow analyzes a commit to main
# and if there is a changeset, will create a PR
# else, it will publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .yarn/**
      - .github/workflows/publish.yml # this file
  workflow_dispatch:

jobs:
  pr-from-commit:
    name: Publish or Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # https://github.com/changesets/action/issues/70#issuecomment-813015134
          # so we can pretend the workflow is not a bot
          persist-credentials: false

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Elm 0.19.1
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1

      - name: Install/Update Dependencies
        run: yarn

      - name: Create PR or publish
        id: changesets
        uses: changesets/action@v1
        with:
          # Not too sure if this is necessary...
          version: yarn changeset version
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
